export enum JobNames {
  AGGREGATE_ATTRIBUTES = 'AGGREGATE_ATTRIBUTES',
  AGGREGATE_COLLECTION_TREND = 'AGGREGATE_COLLECTION_TREND',
  DISCOVER_COLLECTION = 'DISCOVER_COLLECTION',
  DISCOVER_TOKENS = 'DISCOVER_TOKENS',
  FETCH_METADATA = 'FETCH_METADATA',
  QUEUE_DOCUMENT_UPDATE = 'QUEUE_DOCUMENT_UPDATE',
  UPDATE_INDEX = 'UPDATE_INDEX',
  PURCHASE_COMPLETED = 'PURCHASE_COMPLETED',

  PROCESS_ETHEREUM_TRANSACTION = 'PROCESS_ETHEREUM_TRANSACTION',
  PROCESS_ETHEREUM_CREATE_LISTING = 'PROCESS_ETHEREUM_CREATE_LISTING',
  PROCESS_ETHEREUM_TRANSACTION_BACKLOG = 'PROCESS_ETHEREUM_TRANSACTION_BACKLOG',

  PROCESS_ARBITRUM_TRANSACTION_BACKLOG = 'PROCESS_ARBITRUM_TRANSACTION_BACKLOG',
  PROCESS_ARBITRUM_TRANSACTION = 'PROCESS_ARBITRUM_TRANSACTION',

  PROCESS_TELOS_TRANSACTION = 'PROCESS_TELOS_TRANSACTION',
  PROCESS_TELOS_CREATE_LISTING = 'PROCESS_TELOS_CREATE_LISTING',
  PROCESS_TELOS_TRANSACTION_BACKLOG = 'PROCESS_TELOS_TRANSACTION_BACKLOG',

  PROCESS_METIS_TRANSACTION = 'PROCESS_METIS_TRANSACTION',
  PROCESS_METIS_CREATE_LISTING = 'PROCESS_METIS_CREATE_LISTING',
  PROCESS_METIS_TRANSACTION_BACKLOG = 'PROCESS_METIS_TRANSACTION_BACKLOG',

  DISCOVER_NEW_EVM_TOKENS = 'DISCOVER_NEW_EVM_TOKENS',
  DISCOVER_EXTERNAL_EVM_TRANSACTIONS = 'DISCOVER_EXTERNAL_EVM_TRANSACTIONS',
  DOUBLE_CHECK_EXTERNAL_TRANSACTION = 'DOUBLE_CHECK_EXTERNAL_TRANSACTION',
  DISCOVER_MISSING_MEILISEARCH_NFTS = 'DISCOVER_MISSING_MEILISEARCH_NFTS',

  SEND_PASSWORD_RESET_EMAIL = 'SEND_PASSWORD_RESET_EMAIL',
  SEND_REGISTRATION_EMAIL = 'SEND_REGISTRATION_EMAIL',
}
