export enum QueueNames {
  DEFAULT = 'default',
  ETHEREUM_TRANSACTIONS = 'ETHEREUM_TRANSACTIONS',
  TELOS_TRANSACTIONS = 'TELOS_TRANSACTIONS',
  METIS_TRANSACTIONS = 'METIS_TRANSACTIONS',
  SEND_EMAILS = 'SEND_EMAILS',
}
