services:

  db:
    image: postgres:13-alpine
    container_name: codebuilder-postgres-db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - codebuilder-db-data:/var/lib/postgresql/data
    networks:
      - codebuilder-net
    ports:
      - "5434:5432"


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codebuilder-api
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    entrypoint: ["./docker-entrypoint.sh"]
    networks:
      - codebuilder-net



volumes:
  codebuilder-db-data:


networks:
  codebuilder-net:
    external: true