services:

  db:
    image: postgres:15-alpine
    container_name: codebuilder-postgres-db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - codebuilder-net
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    container_name: codebuilder-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - codebuilder-net


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codebuilder-api
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Use docker network alias for Redis
      QUEUE_REDIS_HOST: redis
      # Override application Redis servers config to use redis container
      REDIS_SERVERS: '{"AUTH":{"host":"redis","port":6379,"password":"","tls":false},"CACHE":{"host":"redis","port":6379,"password":"","tls":false}}'
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "==== ENVIRONMENT VARIABLES ===="
        env
        echo "==== REDIS_SERVERS ===="
        echo "$REDIS_SERVERS"
        ./docker-entrypoint.sh
    command: ["pnpm", "start"]
    networks:
      - codebuilder-net



volumes:
  postgres-data:


networks:
  codebuilder-net:
    external: true